### ISSUE TITLE
OPC5/OPC5LS: Expand Predication

### ISSUE THREAD

**Issue by revaldinho** [revaldinho/opc#10]
Revise predication for both OPC5 and OPC5LS

Predication bits/Function
```
P0 P1 PINV             Asm Prefix
 0  0  0  always       [1.]
 0  0  1  never          0.
 0  1  0  Z                 z.
 0  1  1  NZ              nz.
 1  0  0  C                c.
 1  0  1  NC              nc.
 1  1  0  MI               mi.
 1  1  1  PL                pl.
```
   wire       predicate_din = din[PINV] ^ (din[P1] ? (din[P0] ? N_q : C_q) : (din[P0] ? Z_q : 1)); 

New 'N' flag to be added, computed as sign bit of result and under same constraints as the C and Z - i.e. preserve across instructions writing PC, and add as 3rd bit into PSR.

Changes required in all components.

**Comment by revaldinho** [comment]
Correction

wire predicate_din = din[PINV] ^ (din[P1] ? (din[P0] ? N_q : Z_q) : (din[P0] ? C_q : 1));

**Comment by revaldinho** [comment]
Done in OPC5LS but still todo for OPC5

**Comment by BigEd** [comment]
I'm guessing this is done now? Or it's a won't-fix? Or I'm confused?

**Comment by revaldinho** [comment]
Will need to fix this if bringing BCPL back from OPC6/7 to OPC5LS.

No change to existing OPC5LS asm source, but changes the binary encoding and adds the pl., mi. which are used by the SIAL2OPC translation.

**Comment by revaldinho** [comment]
Accidentally reopened.

Predicates all ok in OPC5LS, OPC6, OPC7 ... won't revise the older OPC5 to match,
