### ISSUE TITLE
small correction (?)

### ISSUE THREAD

**Issue by realaxl** [revaldinho/opc#18]
Hi, I guess the first line
```# python3 opc3emu.py <filename.hex> [<filename.memdump>]```
should read
```# python3 opc5emu.py <filename.hex> [<readfile.memdump>] [<writefile.memdump>]```

**Comment by revaldinho** [comment]
Hi Realaxl

Thanks for your comment.

Yes, you're right - the opc5emu.py originally had a lot of cut'n'pasted code from the opc3 and the program name is wrong in the comment. I'll fix that.

The input and output files for the emulator are in the same format - both are a complete hex listing of the machine's memory contents. The only subtle difference between them is the number of hex columns per line, which isn't important.

So, perhaps the comment might better say

# python3 opc5emu.py <filename.init.hex> [ <filename.final.hex> ] ?

Regards

Rich
